version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: webpack
      - dependency-name: webpack-cli
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly